// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [Fir ebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_SRAFF4NWo08fqeM5IHo-5cA0cFjgFZc',
    appId: '1:373149633617:web:bb2c448cf56faac477fc70',
    messagingSenderId: '373149633617',
    projectId: 'reddit-clone-634c3',
    authDomain: 'reddit-clone-634c3.firebaseapp.com',
    storageBucket: 'reddit-clone-634c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW79Ba_7mg1HLEMxdf_yMk8oJxmnK_qik',
    appId: '1:373149633617:android:07aa0bc0fdae4b5b77fc70',
    messagingSenderId: '373149633617',
    projectId: 'reddit-clone-634c3',
    storageBucket: 'reddit-clone-634c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVmyT7qoiz72JYnOWnu6V0gz_9p_ZJ4Ug',
    appId: '1:373149633617:ios:56bb1c84bdc9e9f977fc70',
    messagingSenderId: '373149633617',
    projectId: 'reddit-clone-634c3',
    storageBucket: 'reddit-clone-634c3.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVmyT7qoiz72JYnOWnu6V0gz_9p_ZJ4Ug',
    appId: '1:373149633617:ios:3ed953f87d56994477fc70',
    messagingSenderId: '373149633617',
    projectId: 'reddit-clone-634c3',
    storageBucket: 'reddit-clone-634c3.appspot.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
